### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by joshhartigan** [hedgehog1029/Cookie#2]
you should create a `package.json` so that people can just run `npm install` to get the dependencies automatically, rather than having to get them each one by one, which is boring :frowning:

**Comment by hedgehog1029** [comment]
Will do. I was planning to do this closer to release but I found how annoying it is the other day.

**Comment by joshhartigan** [comment]
a `package.json` shouldn't just be for release, since if anybody else wants to contribute before a release, it's going to help them out too

**Comment by hedgehog1029** [comment]
Fixed in b05287b514274c41d1461ca106caebc3fa8449b7.
